services:
  portfolio:
    image: registry.alfser.com.br/portfolio-janilson:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-janilson
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`janilson.alfser.com.br`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=20261"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.portfolio.service=portfolio"
      - "traefik.http.routers.portfolio.middlewares=security-headers@docker"
    networks:
      - traefik-proxy
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker

networks:
  traefik-proxy:
    external: true
    name: traefik-proxy